name = "vros-api"
main = "worker.js"
compatibility_date = "2024-01-01"

# Account ID (get from Cloudflare dashboard)
# account_id = "YOUR_ACCOUNT_ID"

# Environment variables
[vars]
GITHUB_OWNER = "catnet-systems"
GITHUB_REPO = "vros-bugs"
ALLOWED_ORIGINS = "https://support.vros.cat,https://bugs.vros.cat,http://localhost:5173,http://localhost:3000"

# KV Namespaces (create these via wrangler or dashboard)
# Run these commands to create:
# wrangler kv:namespace create "TOKENS"
# wrangler kv:namespace create "CACHE"  
# wrangler kv:namespace create "RATE_LIMIT"
# Then update the IDs below

[[kv_namespaces]]
binding = "TOKENS"
id = "9990e5e57c584bce9bc5f227678d2ba6"

[[kv_namespaces]]
binding = "CACHE"
id = "b34839f92a2c456493ffd20a01deb050"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "deccc8329002482d861d294404ebb9b5"

# Routes (optional - can also configure in dashboard)
# route = "api.vros.cat/*"

# Custom domain (configure in dashboard)
# workers_dev = false

# Secrets (set via CLI)
# Run these commands:
# wrangler secret put GITHUB_TOKEN
# wrangler secret put ADMIN_KEY

# Development settings
[env.development]
vars = { GITHUB_OWNER = "catnet-systems", GITHUB_REPO = "vros-bugs-dev" }

# Production settings
[env.production]
vars = { GITHUB_OWNER = "catnet-systems", GITHUB_REPO = "vros-bugs" }